const p2teamDict = {
    'Garrett Crochet':'Red Sox',
    'Max Scherzer':'Blue Jays',
    'Max Fried':'Yankees',
    'Chris Sale':'Braves',
    'Blake Snell':'Dodgers',
    'Roki Sasaki':'Dodgers',
    'Paul Skenes':'Pirates',
    'Sandy Alcantara':'Marlins',
    'Carson Spiers':'Reds',
    'Zack Wheeler':'Phillies',
    'Cole Ragans':'Royals',
    'Kodai Senga':'Mets',
    'Pablo Lopez':'Twins',
    'Jordan Montgomery':'Diamondbacks',
    'Jose Quintana':'Mets',
    'Ian Anderson':'Rockies',
    'Shohei Ohtani':'Dodgers',
    'Alex Cobb':'Tigers',
    'Charlie Morton':'Orioles',
    'Adam Ottavino':'Yankees',
    'Devin Williams':'Yankees',
    'JT Brubaker':'Yankees',
    'Marcus Stroman':'Yankees',
    'Shane Baz':'Rays',
    'Corbin Burnes':'Diamondbacks',
    'Tyler ONeill':'Orioles',
    'Sean Manaea':'Giants',
    'Nate Eovaldi':'Rangers',
    'Nathan Eovaldi':'Rangers',
    'Yusei Kikuchi':'Angels',
    'Luis Severino':'Athletics',
    'Matthew Boyd':'Cubs',
    'Justin Verlander':'Giants',
    'Willy Adames':'Giants',
    'Andrew Kittredge':'Orioles',
    'Yimi Garcia':'Blue Jays',
    'Jeff Hoffman':'Blue Jays',
    'Michael Soroka':'Nationals',
    'Trevor Williams':'Nationals',
    'Miguel Castro':'Astros',
    'Tyler Gilbert':'White Sox',
    'Walker Buehler':'Red Sox',
    'Aroldis Chapman':'Red Sox',
    'Patrick Sandoval':'Red Sox',
    'George Kirby':'Mariners',
    'Logan Webb':'Giants',
    'Logan Gilbert':'Mariners',
    'Jacob deGrom':'Rangers',
    'Sonny Gray':'Cardinals',
    'Jack Leiter':'Rangers',
    'Kumar Rocker':'Rangers',
    'Seth Lugo':'Royals',
    'Trevor Rogers':'Marlins',
    'Carlos Rodon':'Yankees',
    'Kyle Wright':'Braves',
    'Tyler Glasnow':'Rays',
    'Brady Singer':'Royals',
    'Patrick Corbin':'Nationals',
    'Jackson Jobe':'Tigers',
    'Ronel Blanco':'Astros',
    'Kris Bubic':'Royals',
    'David Peterson':'Mets',
    'Grant Holmes':'Athletics',
    'Brady Singer':'Cubs',
    'Will Warren':'Yankees',
    'Cade Povich':'Red Sox',
    'Emerson Hancock':'Mariners',
    'German Marquez':'Rockies',
    'Tyler Anderson':'Angels',
    'Chris Paddack':'Twins',
    'Kyle Hart':'Guardians',
    'Sean Newcomb':'Orioles',
    'Luis L Ortiz':'Pirates',
    'Miles Mikolas':'Cardinals',
    'Jordan Hicks':'Cardinals',
    'Martin Perez':'Twins',
    'Aaron Ashby':'Brewers',
    'Bryce Miller':'Mariners',
    'Dane Dunning':'Rangers',
    'Yohander Mendez':'Rangers',
    'Javier Assad':'Cubs',
    'Gavin Williams':'Guardians',
    'Matt Manning':'Tigers',
    'Tanner Houck':'Red Sox',
    'Tyler Beede':'Giants',
    'Bailey Ober':'Twins',
    'Zach Plesac':'Guardians',
    'Cole Irvin':'Orioles',
    'Reid Detmers':'Angels',
    'Nick Lodolo':'Reds',
    'Brailyn Marquez':'Cubs',
    'Zack Thompson':'Pirates',
    'Landen Roupp':'Giants',
    'Yusei Kikuchi':'Angels',
    'Ryan Johnson':'Angels',
    'Andrew Painter':'Phillies',
    'Hayden Birdsong':'Giants',
    'Ryan Weathers':'Marlins',
    'Dylan Crews':'Nationals',
    'Kristian Campbell':'Red Sox',
    'Matt Shaw':'Cubs',
    'Ben Brown':'Cubs',
    'Bubba Chandler':'Pirates',
    'Noah Schultz':'White Sox',
    'Rhett Lowder':'Reds',
    'Quinn Mathews':'Cardinals',
    'Hurston Waldrep':'Braves',
    'Tink Hence':'Cardinals',
    'Cade Horton':'Cubs',
    'Mick Abel':'Phillies',
    'Christian Scott':'Mets',
    'Chase Hampton':'Yankees',
    'Tarik Skubal':'Tigers',
    'Jose Berrios':'Blue Jays',
    'Michael Lorenzen':'Royals',
    'Chad Patrick':'Brewers',
    'Kyle Hendricks':'Angels',
    'Matthew Liberatore':'Cardinals',
    'Michael King':'Padres',
    'Logan Allen':'Guardians',
    'Casey Mize':'Tigers',
    'Simeon Woods Richardson':'Twins',
    'Shane Smith':'White Sox',
    'Hayden Wesneski':'Astros',
    'Justin Steele':'Cubs',
    'Dustin May':'Dodgers',
}

function player2team(player) {
    try {
        return p2teamDict[player]
    } catch {
        return "-"
    }
}


export default { player2team }